"""add demo_analysis_request_logs table

Revision ID: e560113bd54a
Revises: 850952a10a94
Create Date: 2026-08-21 17:05:00.778356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e560113bd54a'
down_revision: Union[str, None] = '850952a10a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_analysis_request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_analysis_request_logs_ip_address'), 'demo_analysis_request_logs', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demo_analysis_request_logs_ip_address'), table_name='demo_analysis_request_logs')
    op.drop_table('demo_analysis_request_logs')
    # ### end Alembic commands ###
