<script setup lang="ts">
import { ref, watch } from 'vue'

import AppAlert from '@/components/ui/AppAlert.vue'
import AppModal from '@/components/ui/AppModal.vue'
import { usePortfolioStore } from '@/stores/portfolio'
import { getApiErrorMessage } from '@/utils/apiError'

const props = defineProps<{
  open: boolean
  portfolioId: number
}>()

const emit = defineEmits<{ close: [] }>()

const portfolioStore = usePortfolioStore()

const loading = ref(false)
const report = ref('')
const error = ref('')

async function runAnalysis() {
  loading.value = true
  error.value = ''
  report.value = ''
  try {
    report.value = await portfolioStore.analyzePortfolio(props.portfolioId)
  } catch (err) {
    error.value = getApiErrorMessage(err, 'Unable to analyze this portfolio right now.')
  } finally {
    loading.value = false
  }
}

// Starts the analysis as soon as the modal opens -- one-shot, no separate "run" click.
watch(
  () => props.open,
  (isOpen) => {
    if (isOpen) runAnalysis()
  },
)
</script>

<template>
  <AppModal :open="open" title="Portfolio analysis" size="lg" @close="emit('close')">
    <div class="flex flex-col gap-4">
      <p v-if="loading" class="flex items-center gap-2 py-6 text-sm text-ink-muted">
        <span
          class="size-4 shrink-0 animate-spin rounded-full border-2 border-current border-r-transparent"
          aria-hidden="true"
        />
        Analyzing your portfolio — this can take up to 15 seconds…
      </p>

      <AppAlert v-else-if="error">{{ error }}</AppAlert>

      <template v-else>
        <p class="whitespace-pre-wrap text-sm leading-relaxed text-ink">{{ report }}</p>
        <AppAlert variant="info">
          This analysis is generated by AI from your portfolio data. It is not financial advice.
        </AppAlert>
      </template>
    </div>
  </AppModal>
</template>
